"""Execution plane: structured actions only, never raw shell."""

from .discovery import (
    DISCOVERY_ADAPTERS,
    OsFingerprintAdapter,
    PortScanAdapter,
    ServiceDetectAdapter,
)
from .tool_exec import TOOL_EXEC_ADAPTERS, ToolExecAdapter
from .re import (
    RE_ADAPTERS,
    BinaryInfoAdapter,
    ChecksecAdapter,
    DisasmAdapter,
    StringDumpAdapter,
    SymbolDumpAdapter,
)
from .hunters import (
    HUNTER_ADAPTERS,
    NiktoAdapter,
    NucleiScanAdapter,
    WpscanAdapter,
    SearchsploitAdapter,
    TcpdumpCaptureAdapter,
    LynisAuditAdapter,
)
from .adapters import (
    CertTransparencyAdapter,
    HeaderAuditAdapter,
    HttpProbeAdapter,
    NucleiAdapter,
    PassiveDnsMultiAdapter,
    SmbEnumAdapter,
    TlsPostureAdapter,
    TracerouteAdapter,
    WhoisAdapter,
)
from .broker import (
    ActionRequest,
    Adapter,
    AdapterRegistry,
    BUILTIN_ADAPTERS,
    EchoAdapter,
    ExecutionBroker,
    ExecutionResult,
    GateResult,
    NmapDiscoveryAdapter,
    PassiveDnsAdapter,
)

__all__ = [
    "ActionRequest",
    "DISCOVERY_ADAPTERS",
    "HUNTER_ADAPTERS",
    "NucleiScanAdapter",
    "NiktoAdapter",
    "WpscanAdapter",
    "SearchsploitAdapter",
    "TcpdumpCaptureAdapter",
    "LynisAuditAdapter",
    "OsFingerprintAdapter",
    "PortScanAdapter",
    "ServiceDetectAdapter",
    "TOOL_EXEC_ADAPTERS",
    "RE_ADAPTERS",
    "BinaryInfoAdapter",
    "ChecksecAdapter",
    "DisasmAdapter",
    "StringDumpAdapter",
    "SymbolDumpAdapter",
    "ToolExecAdapter",
    "Adapter",
    "AdapterRegistry",
    "BUILTIN_ADAPTERS",
    "CertTransparencyAdapter",
    "EchoAdapter",
    "ExecutionBroker",
    "ExecutionResult",
    "GateResult",
    "HeaderAuditAdapter",
    "HttpProbeAdapter",
    "NmapDiscoveryAdapter",
    "NucleiAdapter",
    "PassiveDnsAdapter",
    "PassiveDnsMultiAdapter",
    "SmbEnumAdapter",
    "TlsPostureAdapter",
    "TracerouteAdapter",
    "WhoisAdapter",
]
